apiVersion: v1
kind: Service
metadata:
  name: service-a
  labels:
    app: service-a
spec:
  type: NodePort
  ports:
    - targetPort: 80
      name: http
      port: 80
    - targetPort: 1883
      name: mqtt
      port: 1883
  selector:
    app: service-a
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a
  labels:
    app: service-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-a
  template:
    metadata:
      labels:
        app: service-a
    spec:
      containers:
      - name: service-a
        image: service-a
        ports:
        - containerPort: 80
        - containerPort: 1883
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 1
