apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
  labels:
    app: fastapi-service
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
  selector:
    app: fastapi-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-service
  labels:
    app: fastapi-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-service
  template:
    metadata:
      labels:
        app: fastapi-service
    spec:
      containers:
      - name: fastapi-service
        image: fastapi-service
        ports:
        - containerPort: 80
        env:
        - name: STRING_TO_DISPLAY
          value: "Another World"
